### ISSUE TITLE
netif_add: failed when trying to connect to VPN

### ISSUE THREAD

**Issue by MiningPickaxe** [droscy/esp_wireguard#2]
Hello,
thank you very much for starting this project, I have been looking for something like this for some time now :) 

When trying to connect to the VPN I get the following error:
```
[D][esp-idf:000]: E (7532) esp_wireguard: netif_add: failed
[D][esp-idf:000]: E (7533) esp_wireguard: esp_wireguard_netif_create: ESP_FAIL
[W][wireguard:193]: cannot start WireGuard connection, error code -1
```
My config for ESPHome is the following (sensitive values redacted)
```
esphome:
  name: esphome-web-640fc8
  friendly_name: Test Rolladen Ried VPN

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "something"

ota:

# Define wireguard external source
external_components:
  - source:
      type: git
      url: https://github.com/droscy/esphome
      ref: wireguard/main
    components:
      - wireguard
      - wireguard_status
      - wireguard_handshake

# Setup a time source.
# Do not use 'homeassistant' platform if Home Assistant is on the remote
# peer because the time synchronization is a prerequisite to establish
# the vpn link.
time:
  - platform: sntp

# Setup WireGuard
wireguard:
  address: 192.168.200.205
  private_key: private_key=something
  peer_endpoint: homeip.something.de
  peer_public_key: public_key=something
  netmask: 255.255.255.255
  peer_port: 53949

  # optional pre-shared key
  peer_preshared_key: shared_key=something

  # optional keepalive in seconds (disabled by default)
  peer_persistent_keepalive: 25s

  # optional list of allowed ip/mask (the default is to allow any host if omitted)
  peer_allowed_ips:
    - 192.168.200.0/24
    - 0.0.0.0/0

  # reboot the board if remote peer in unreachable (default to 15min, set to 0s to disable)
  reboot_timeout: 15min

wifi:
  ssid: Mobiltelefon
  password: something

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-640Fc8"
    password: "something"    
```

During boot I get the following output:
```
[I][logger:262]: Log initialized
[C][ota:469]: There have been 0 suspected unsuccessful boot attempts.
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[C][wifi:038]: Setting up WiFi...
[C][wifi:039]:   Local MAC: A0:B7:65:64:0F:C8
[D][wifi:387]: Starting scan...
[D][wifi:402]: Found networks:
[I][wifi:446]: - 'Mobiltelefon' [redacted]▂▄▆█
[D][wifi:447]:     Channel: 1
[D][wifi:448]:     RSSI: -30 dB
[D][wifi:451]: - [redacted] [redacted]▂▄▆█
[D][wifi:451]: - [redacted] [redacted]▂▄▆█
[D][wifi:451]: - [redacted] [redacted]▂▄▆█
[D][wifi:451]: - [redacted] [redacted]▂▄▆█
[D][wifi:451]: - [redacted] [redacted]▂▄▆█
[I][wifi:258]: WiFi Connecting to 'Mobiltelefon'...
[I][wifi:519]: WiFi Connected!
[C][wifi:363]:   Local MAC: A0:B7:65:64:0F:C8
[C][wifi:364]:   SSID: [redacted]
[C][wifi:365]:   IP Address: 172.20.10.2
[C][wifi:367]:   BSSID: [redacted]
[C][wifi:368]:   Hostname: 'esphome-web-640fc8'
[C][wifi:370]:   Signal strength: -23 dB ▂▄▆█
[C][wifi:374]:   Channel: 1
[C][wifi:375]:   Subnet: 255.255.255.240
[C][wifi:376]:   Gateway: 172.20.10.1
[C][wifi:377]:   DNS1: 172.20.10.1
[C][wifi:378]:   DNS2: 0.0.0.0
[D][wifi:528]: Disabling AP...
[C][ota:093]: Over-The-Air Updates:
[C][ota:094]:   Address: esphome-web-640fc8.local:3232
[C][api:025]: Setting up Home Assistant API server...
[C][sntp:028]: Setting up SNTP...
[D][wireguard:035]: initializing WireGuard...
[I][wireguard:051]: WireGuard initialized
[D][wireguard:169]: WireGuard is waiting for system time to be synchronized
[I][app:062]: setup() finished successfully!
[D][wireguard:078]: WireGuard remote peer is offline (latest handshake timestamp not available)
[I][app:102]: ESPHome version 2023.5.5 compiled on Jun  3 2023, 16:45:18
[C][wifi:505]: WiFi:
[C][wifi:363]:   Local MAC: A0:B7:65:64:0F:C8
[C][wifi:364]:   SSID: [redacted]
[C][wifi:365]:   IP Address: 172.20.10.2
[C][wifi:367]:   BSSID: [redacted]
[C][wifi:368]:   Hostname: 'esphome-web-640fc8'
[C][wifi:370]:   Signal strength: -25 dB ▂▄▆█
[C][wifi:374]:   Channel: 1
[C][wifi:375]:   Subnet: 255.255.255.240
[C][wifi:376]:   Gateway: 172.20.10.1
[C][wifi:377]:   DNS1: 172.20.10.1
[C][wifi:378]:   DNS2: 0.0.0.0
[C][logger:301]: Logger:
[C][logger:302]:   Level: DEBUG
[C][logger:303]:   Log Baud Rate: 115200
[C][logger:305]:   Hardware UART: UART0
[C][captive_portal:088]: Captive Portal:
[C][mdns:108]: mDNS:
[C][mdns:109]:   Hostname: esphome-web-640fc8
[C][ota:093]: Over-The-Air Updates:
[C][ota:094]:   Address: esphome-web-640fc8.local:3232
[C][api:138]: API Server:
[C][api:139]:   Address: esphome-web-640fc8.local:6053
[C][api:141]:   Using noise encryption: YES
[C][sntp:053]: SNTP Time:
[C][sntp:054]:   Server 1: '0.pool.ntp.org'
[C][sntp:055]:   Server 2: '1.pool.ntp.org'
[C][sntp:056]:   Server 3: '2.pool.ntp.org'
[C][sntp:057]:   Timezone: 'CET-1CEST,M3.5.0,M10.5.0/3'
[C][wireguard:092]: WireGuard:
[C][wireguard:093]:   address: 192.168.200.205
[C][wireguard:094]:   netmask: 255.255.255.255
[C][wireguard:095]:   private key: priva[...]=
[C][wireguard:096]:   peer endpoint: homeip.something.de
[C][wireguard:097]:   peer port: 53949
[C][wireguard:098]:   peer public key: public_key=something
[C][wireguard:101]:   peer preshared key: share[...]=
[C][wireguard:102]:   peer allowed ips:
[C][wireguard:104]:     - 0.0.0.0/0.0.0.0
[C][wireguard:107]:   peer persistent keepalive: 25s
[C][wireguard:109]:   reboot timeout: 900s
[D][sntp:078]: Synchronized time: 2023-06-03 16:46:50
[D][wireguard:178]: starting WireGuard connection...
[D][esp-idf:000]: E (7532) esp_wireguard: netif_add: failed

[D][esp-idf:000]: E (7533) esp_wireguard: esp_wireguard_netif_create: ESP_FAIL

[W][wireguard:193]: cannot start WireGuard connection, error code -1
[D][wireguard:078]: WireGuard remote peer is offline (latest handshake timestamp not available)
[D][wireguard:078]: WireGuard remote peer is offline (latest handshake timestamp not available)
[D][wireguard:078]: WireGuard remote peer is offline (latest handshake timestamp not available)
[...]
```
